spring.application.name=AutoEscolaS164
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/autoescolas164
spring.datasource.username=root
spring.datasource.password=senai
api.security.token.secret=12345678